# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ELECTRIC_FIELD_V2.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(10, 0, 961, 501))
        self.mdiArea.setMinimumSize(QtCore.QSize(961, 501))
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.TabbedView)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.EP_lineEdit = QtWidgets.QLineEdit(self.subwindow)
        self.EP_lineEdit.setGeometry(QtCore.QRect(240, 310, 631, 25))
        self.EP_lineEdit.setObjectName("EP_lineEdit")
        self.DM_lineEdit = QtWidgets.QLineEdit(self.subwindow)
        self.DM_lineEdit.setGeometry(QtCore.QRect(240, 270, 631, 25))
        self.DM_lineEdit.setObjectName("DM_lineEdit")
        self.layoutWidget = QtWidgets.QWidget(self.subwindow)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 40, 771, 159))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.a_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.a_lineEdit.setText("")
        self.a_lineEdit.setObjectName("a_lineEdit")
        self.gridLayout_2.addWidget(self.a_lineEdit, 1, 1, 1, 1)
        self.a_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.a_comboBox.setObjectName("a_comboBox")
        self.a_comboBox.addItem("")
        self.a_comboBox.addItem("")
        self.a_comboBox.addItem("")
        self.a_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.a_comboBox, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.theta_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.theta_lineEdit.setObjectName("theta_lineEdit")
        self.gridLayout_2.addWidget(self.theta_lineEdit, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.r_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.r_lineEdit.setObjectName("r_lineEdit")
        self.gridLayout_2.addWidget(self.r_lineEdit, 0, 1, 1, 1)
        self.r_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.r_comboBox.setObjectName("r_comboBox")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.r_comboBox, 0, 2, 1, 1)
        self.q_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.q_lineEdit.setText("")
        self.q_lineEdit.setObjectName("q_lineEdit")
        self.gridLayout_2.addWidget(self.q_lineEdit, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.theta_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.theta_comboBox.setObjectName("theta_comboBox")
        self.theta_comboBox.addItem("")
        self.theta_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.theta_comboBox, 2, 2, 1, 1)
        self.q_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.q_comboBox.setObjectName("q_comboBox")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.q_comboBox, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.subwindow)
        self.label_9.setGeometry(QtCore.QRect(100, 390, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.subwindow)
        self.label_10.setGeometry(QtCore.QRect(100, 350, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.subwindow)
        self.label_11.setGeometry(QtCore.QRect(110, 270, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.subwindow)
        self.label_12.setGeometry(QtCore.QRect(100, 310, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.AP_lineEdit = QtWidgets.QLineEdit(self.subwindow)
        self.AP_lineEdit.setGeometry(QtCore.QRect(240, 350, 631, 25))
        self.AP_lineEdit.setObjectName("AP_lineEdit")
        self.Error_lineEdit = QtWidgets.QLineEdit(self.subwindow)
        self.Error_lineEdit.setGeometry(QtCore.QRect(240, 390, 631, 25))
        self.Error_lineEdit.setObjectName("Error_lineEdit")
        self.calculate_pushButton = QtWidgets.QPushButton(self.subwindow)
        self.calculate_pushButton.setGeometry(QtCore.QRect(410, 220, 151, 31))
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        self.help_subwindow = QtWidgets.QWidget()
        self.help_subwindow.setObjectName("help_subwindow")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.help_subwindow)
        self.textBrowser_2.setGeometry(QtCore.QRect(5, 1, 941, 441))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.about_subwindow = QtWidgets.QWidget()
        self.about_subwindow.setObjectName("about_subwindow")
        self.textBrowser = QtWidgets.QTextBrowser(self.about_subwindow)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 951, 451))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Dipole's Electric Field Calculator"))
        self.label_5.setText(_translate("MainWindow", "Distance between POI and center of dipole, a: "))
        self.a_comboBox.setItemText(0, _translate("MainWindow", "meters"))
        self.a_comboBox.setItemText(1, _translate("MainWindow", "centimeters"))
        self.a_comboBox.setItemText(2, _translate("MainWindow", "millimeters"))
        self.a_comboBox.setItemText(3, _translate("MainWindow", "angstroms"))
        self.label_6.setText(_translate("MainWindow", "Angle between POI and positive charge from center of dipole, theta: "))
        self.label_7.setText(_translate("MainWindow", "Distance between POI and center of dipole, r: "))
        self.r_comboBox.setItemText(0, _translate("MainWindow", "meters"))
        self.r_comboBox.setItemText(1, _translate("MainWindow", "centimeters"))
        self.r_comboBox.setItemText(2, _translate("MainWindow", "millimeters"))
        self.r_comboBox.setItemText(3, _translate("MainWindow", "angstroms"))
        self.label_8.setText(_translate("MainWindow", "Either charge of dipole, q:"))
        self.theta_comboBox.setItemText(0, _translate("MainWindow", "degrees"))
        self.theta_comboBox.setItemText(1, _translate("MainWindow", "radians"))
        self.q_comboBox.setItemText(0, _translate("MainWindow", "Coulomb"))
        self.q_comboBox.setItemText(1, _translate("MainWindow", "microCoulomb"))
        self.q_comboBox.setItemText(2, _translate("MainWindow", "electronCharge"))
        self.q_comboBox.setItemText(3, _translate("MainWindow", "milliCoulomb"))
        self.q_comboBox.setItemText(4, _translate("MainWindow", "nanoCoulomb"))
        self.q_comboBox.setItemText(5, _translate("MainWindow", "picoColomb"))
        self.label_9.setText(_translate("MainWindow", "Error :"))
        self.label_10.setText(_translate("MainWindow", "Approx Potential :"))
        self.label_11.setText(_translate("MainWindow", "Dipole Moment :"))
        self.label_12.setText(_translate("MainWindow", "Exact Potential :"))
        self.calculate_pushButton.setText(_translate("MainWindow", "Calculate"))
        self.help_subwindow.setWindowTitle(_translate("MainWindow", "Help"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Abyssinica SIL\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-&gt; <b>What is an Electric Dipole?<\b></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">$ - An Electric Dipole is defined as a pair of two equal and opposite charges that are <a href=\"https://en.wikipedia.org/wiki/Infinitesimal\"><span style=\" text-decoration: underline; color:#0000ff;\">infinitesimally</span></a> close together. This is unrealistic, as real dipoles have separated charge. By definition, the dipole\'s direction points from the negative charge towards the positive charge.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-&gt; <b>What is Dipole Moment?<\b></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">$ - The <span style=\" font-weight:600;\">electric dipole moment</span> is a measure of the separation of positive and negative <a href=\"https://en.wikipedia.org/wiki/Electrical_charge\"><span style=\" text-decoration: underline; color:#0000ff;\">electrical charges</span></a> within a system, that is, a measure of the system\'s overall <a href=\"https://en.wikipedia.org/wiki/Chemical_polarity\"><span style=\" text-decoration: underline; color:#0000ff;\">polarity</span></a>. The <a href=\"https://en.wikipedia.org/wiki/International_System_of_Units\"><span style=\" text-decoration: underline; color:#0000ff;\">SI units</span></a> for electric <a href=\"https://en.wikipedia.org/wiki/Dipole\"><span style=\" text-decoration: underline; color:#0000ff;\">dipole</span></a> moment are <a href=\"https://en.wikipedia.org/wiki/Coulomb\"><span style=\" text-decoration: underline; color:#0000ff;\">coulomb</span></a>-<a href=\"https://en.wikipedia.org/wiki/Meter\"><span style=\" text-decoration: underline; color:#0000ff;\">meter</span></a> (C⋅m). However, a commonly used unit in atomic physics and chemistry is the <a href=\"https://en.wikipedia.org/wiki/Debye\"><span style=\" text-decoration: underline; color:#0000ff;\">debye</span></a> (D). </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-&gt; <b>How to calculate Dipole Moment of an Electric Dipole?<\b></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">$ - Electric Dipole is calculated using the following formula-</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                  p = q*(2*a)                     where, q = magnitude of either charge</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                    a = distance between center of dipole and either charge</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-&gt; <b>How to calculate Electric Field due to an Electric Dipole?<\b></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">$ - Complete guide to calculate Electric Field can be found from <a href=\"https://byjus.com/physics/dipole-electric-field/\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a>.</p></body></html>"))
        self.about_subwindow.setWindowTitle(_translate("MainWindow", "About"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Abyssinica SIL\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">ELECTRIC FIELD CALCULATOR</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\"><br /></span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; color:#000000;\">This project is made by Chetan Goyal. It\'s complete </span><a href=\"https://github.com/Chetan-Goyal/Electric_Field_Calculator\"><span style=\" font-size:26pt; text-decoration: underline; color:#0000ff;\">source code</span></a><span style=\" font-size:20pt; color:#000000;\"> is available on Github. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; color:#000000;\">It is made with Python using PyQt5. </span></p></body></html>"))
