# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EFP_Calculator_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calculate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_pushButton.setGeometry(QtCore.QRect(340, 200, 151, 31))
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        self.DM_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.DM_lineEdit.setGeometry(QtCore.QRect(170, 250, 631, 25))
        self.DM_lineEdit.setObjectName("DM_lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.EP_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.EP_lineEdit.setGeometry(QtCore.QRect(170, 290, 631, 25))
        self.EP_lineEdit.setObjectName("EP_lineEdit")
        self.AP_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.AP_lineEdit.setGeometry(QtCore.QRect(170, 330, 631, 25))
        self.AP_lineEdit.setObjectName("AP_lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Error_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Error_lineEdit.setGeometry(QtCore.QRect(170, 370, 631, 25))
        self.Error_lineEdit.setObjectName("Error_lineEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 370, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Keraleeyam")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 771, 159))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.a_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.a_lineEdit.setText("")
        self.a_lineEdit.setObjectName("a_lineEdit")
        self.gridLayout.addWidget(self.a_lineEdit, 1, 1, 1, 1)
        self.a_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.a_comboBox.setObjectName("a_comboBox")
        self.a_comboBox.addItem("")
        self.a_comboBox.addItem("")
        self.a_comboBox.addItem("")
        self.a_comboBox.addItem("")
        self.gridLayout.addWidget(self.a_comboBox, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.theta_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.theta_lineEdit.setObjectName("theta_lineEdit")
        self.gridLayout.addWidget(self.theta_lineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.r_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.r_lineEdit.setObjectName("r_lineEdit")
        self.gridLayout.addWidget(self.r_lineEdit, 0, 1, 1, 1)
        self.r_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.r_comboBox.setObjectName("r_comboBox")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.gridLayout.addWidget(self.r_comboBox, 0, 2, 1, 1)
        self.q_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.q_lineEdit.setText("")
        self.q_lineEdit.setObjectName("q_lineEdit")
        self.gridLayout.addWidget(self.q_lineEdit, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.theta_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.theta_comboBox.setObjectName("theta_comboBox")
        self.theta_comboBox.addItem("")
        self.theta_comboBox.addItem("")
        self.gridLayout.addWidget(self.theta_comboBox, 2, 2, 1, 1)
        self.q_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.q_comboBox.setObjectName("q_comboBox")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.q_comboBox.addItem("")
        self.gridLayout.addWidget(self.q_comboBox, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculate_pushButton.setText(_translate("MainWindow", "Calculate"))
        self.label_5.setText(_translate("MainWindow", "Dipole Moment :"))
        self.label_6.setText(_translate("MainWindow", "Exact Potential :"))
        self.label_7.setText(_translate("MainWindow", "Approx Potential :"))
        self.label_8.setText(_translate("MainWindow", "Error :"))
        self.label_2.setText(_translate("MainWindow", "Distance between POI and center of dipole, a: "))
        self.a_comboBox.setItemText(0, _translate("MainWindow", "meters"))
        self.a_comboBox.setItemText(1, _translate("MainWindow", "centimeters"))
        self.a_comboBox.setItemText(2, _translate("MainWindow", "milimeters"))
        self.a_comboBox.setItemText(3, _translate("MainWindow", "angstroms"))
        self.label_3.setText(_translate("MainWindow", "Angle between POI and positive charge from center of dipole, theta: "))
        self.label.setText(_translate("MainWindow", "Distance between POI and center of dipole, r: "))
        self.r_comboBox.setItemText(0, _translate("MainWindow", "meters"))
        self.r_comboBox.setItemText(1, _translate("MainWindow", "centimeters"))
        self.r_comboBox.setItemText(2, _translate("MainWindow", "milimeters"))
        self.r_comboBox.setItemText(3, _translate("MainWindow", "angstroms"))
        self.label_4.setText(_translate("MainWindow", "Either charge of dipole, q:"))
        self.theta_comboBox.setItemText(0, _translate("MainWindow", "degrees"))
        self.theta_comboBox.setItemText(1, _translate("MainWindow", "radians"))
        self.q_comboBox.setItemText(0, _translate("MainWindow", "Couloumb"))
        self.q_comboBox.setItemText(1, _translate("MainWindow", "microCouloumb"))
        self.q_comboBox.setItemText(2, _translate("MainWindow", "electronzvolt"))
        self.q_comboBox.setItemText(3, _translate("MainWindow", "miliCouloumb"))
        self.q_comboBox.setItemText(4, _translate("MainWindow", "nanoCouloumb"))
        self.q_comboBox.setItemText(5, _translate("MainWindow", "picoColoumb"))
